# Generated by Django 2.0.7 on 2018-07-09 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarvis', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lista',
        ),
        migrations.AddField(
            model_name='itenslista',
            name='ano',
            field=models.PositiveSmallIntegerField(default=2018),
        ),
        migrations.AddField(
            model_name='itenslista',
            name='semana',
            field=models.PositiveSmallIntegerField(default=28),
        ),
    ]
