# Generated by Django 2.0.7 on 2018-07-08 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarvis', '0002_auto_20180708_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itenslista',
            name='quantidade',
            field=models.CharField(default='', max_length=10),
        ),
    ]
