# Generated by Django 2.0.7 on 2018-07-13 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarvis', '0003_auto_20180709_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itenslista',
            name='categoria',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='itenslista',
            name='quantidade',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
