# Generated by Django 2.0.7 on 2018-07-08 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jarvis', '0003_auto_20180708_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itenslista',
            name='quantidade',
        ),
    ]
