# Generated by Django 2.0.7 on 2018-07-13 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarvis', '0004_auto_20180713_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersTelegram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('chat_id', models.CharField(max_length=10)),
            ],
        ),
    ]
