# Generated by Django 2.0.7 on 2018-07-08 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarvis', '0004_remove_itenslista_quantidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='itenslista',
            name='quantidade',
            field=models.BooleanField(default=False),
        ),
    ]
