# Generated by Django 2.0.7 on 2018-07-08 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarvis', '0005_itenslista_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itenslista',
            name='quantidade',
            field=models.CharField(default='', max_length=10),
        ),
    ]
