# Generated by Django 2.0.7 on 2018-07-15 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarvis', '0006_auto_20180715_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='itenslista',
            name='secao',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(10, 'Cereais'), (20, 'Mercearia'), (30, 'Frios'), (40, 'Hortifruti'), (50, 'Carnes'), (60, 'Higiene'), (70, 'Limpeza'), (80, 'Bebidas'), (90, 'Outros')], default=90, verbose_name='seção'),
        ),
    ]
