# Generated by Django 2.0.7 on 2018-07-16 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarvis', '0008_remove_itenslista_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstelegram',
            name='username',
        ),
        migrations.AddField(
            model_name='userstelegram',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
