# Generated by Django 3.0.7 on 2020-06-27 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarvis', '0010_auto_20180721_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsReported',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='itenslista',
            name='ano',
            field=models.PositiveSmallIntegerField(default=2020),
        ),
        migrations.AlterField(
            model_name='itenslista',
            name='secao',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(10, 'CEREAIS'), (20, 'MERCEARIA'), (30, 'FRIOS'), (35, 'PADARIA'), (40, 'HORTIFRUTI'), (50, 'CARNES'), (60, 'HIGIENE'), (70, 'LIMPEZA'), (80, 'BEBIDAS'), (90, 'OUTROS')], default=90, verbose_name='seção'),
        ),
        migrations.AlterField(
            model_name='itenslista',
            name='semana',
            field=models.PositiveSmallIntegerField(default=25),
        ),
    ]
