# Generated by Django 3.0.7 on 2020-06-27 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarvis', '0011_auto_20200626_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsreported',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
